### ISSUE TITLE
CloudMQTT integration

### ISSUE THREAD

**Issue by rnlascano** [richibrics/PyMonitorMQTT#6]
Hello, as you told me to, i opened this issue to find out how to integrate this monitor system with cloudmqtt. Thanks.

**Comment by richibrics** [comment]
Well, have you already created a cloudmqtt instance ?

**Comment by rnlascano** [comment]
Yes, i have. Used to use it for Owntracks integration wiht hassio. Still active

**Comment by richibrics** [comment]
Well, if you have an instance then you have

- an username
- your own password
- broker address (given by cloudmqtt)

Right ?

**Comment by rnlascano** [comment]
Yes, exactly

**Comment by richibrics** [comment]
Then it works like any other component/client:
in configuration.yaml set (follow schema written in README):
broker, username, password.
Then in sensors list place sensors you'd like to have and the same with the commands (TO USE THE COMMANDS YOU MUST ENABLE Os Sensor AND DesktopEnvironment Sensor: if you don't want to send these 2 data to your broker because you don't need them, take a look in the schema in README and add 'dont_send' option to those 2 sensors)

**Comment by richibrics** [comment]
Closed due to inactivity
